# Generated by Django 4.2.6 on 2023-11-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaQuimico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion_quimicos', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida'), ('Inventario', 'Inventario')], max_length=10)),
                ('fecha_ingreso_egreso', models.DateField()),
                ('nombre_buque_destinado', models.CharField(max_length=255)),
                ('taller', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad_bidones_ocn_01', models.IntegerField()),
                ('cantidad_bidones_ocn_08', models.IntegerField()),
                ('cantidad_bidones_acido_clorhidrico', models.IntegerField()),
                ('cantidad_bidones_hipoclorito', models.IntegerField()),
                ('cantidad_bidones_hold_coat', models.IntegerField()),
                ('stock_bines', models.CharField(choices=[('Lleno', 'Lleno (1000 lts) aprox'), ('Medio', 'Medio (500 lts) aprox'), ('Vacio', 'Vacio')], max_length=10)),
                ('status_bines', models.CharField(choices=[('Lleno', 'Lleno'), ('Medio', 'Medio'), ('Vacio', 'Vacio')], max_length=10)),
            ],
        ),
    ]
