# Generated by Django 4.2.6 on 2023-11-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_fichaquimico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fichaquimico',
            old_name='fecha_ingreso_egreso',
            new_name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='fichaquimico',
            name='accion_quimicos',
        ),
        migrations.RemoveField(
            model_name='fichaquimico',
            name='cantidad_bidones_acido_clorhidrico',
        ),
        migrations.RemoveField(
            model_name='fichaquimico',
            name='cantidad_bidones_hipoclorito',
        ),
        migrations.RemoveField(
            model_name='fichaquimico',
            name='cantidad_bidones_hold_coat',
        ),
        migrations.RemoveField(
            model_name='fichaquimico',
            name='cantidad_bidones_ocn_01',
        ),
        migrations.RemoveField(
            model_name='fichaquimico',
            name='cantidad_bidones_ocn_08',
        ),
        migrations.RemoveField(
            model_name='fichaquimico',
            name='nombre_buque_destinado',
        ),
        migrations.RemoveField(
            model_name='fichaquimico',
            name='status_bines',
        ),
        migrations.RemoveField(
            model_name='fichaquimico',
            name='stock_bines',
        ),
        migrations.RemoveField(
            model_name='fichaquimico',
            name='taller',
        ),
        migrations.AddField(
            model_name='fichaquimico',
            name='capacidad_bines',
            field=models.CharField(default='Lleno (1000 lts) aprox', max_length=255),
        ),
        migrations.AddField(
            model_name='fichaquimico',
            name='lugar_almacenamiento',
            field=models.CharField(default='Taller', max_length=255),
        ),
        migrations.AddField(
            model_name='fichaquimico',
            name='tipo_quimico',
            field=models.CharField(choices=[('OCN 01', 'OCN 01'), ('OCN 08', 'OCN 08'), ('Acido Clorhídrico', 'Acido Clorhídrico'), ('Hipoclorito', 'Hipoclorito'), ('Hold Coat', 'Hold Coat')], default='OCN 01', max_length=50),
        ),
    ]
