# Generated by Django 4.2.6 on 2023-11-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_rename_fecha_ingreso_egreso_fichaquimico_fecha_registro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('', 'Seleccione una marca'), ('Marca1', 'Marca1'), ('Marca2', 'Marca2')], max_length=255)),
                ('fecha_ingreso', models.DateField()),
                ('modelo', models.CharField(max_length=255)),
                ('patente', models.CharField(max_length=10)),
                ('chasis', models.CharField(max_length=255)),
                ('tipo_vehiculo', models.CharField(choices=[('', 'Seleccione un tipo de vehículo'), ('Auto', 'Auto'), ('Camioneta', 'Camioneta'), ('Furgon', 'Furgon'), ('Camion', 'Camion')], max_length=50)),
                ('tipo_combustible', models.CharField(choices=[('', 'Seleccione un tipo de combustible'), ('Diesel', 'Diesel'), ('Bencinero', 'Bencinero')], max_length=50)),
            ],
        ),
    ]
