# Generated by Django 4.2.6 on 2023-11-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_alter_fichavehiculo_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaHerramientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=255)),
                ('fecha_ingreso', models.DateField()),
                ('modelo', models.CharField(max_length=255)),
                ('cantidad_herramientas', models.IntegerField()),
                ('tipo_herramienta', models.CharField(choices=[('Manual', 'Manual'), ('Mecanico', 'Mecanico')], max_length=50)),
            ],
        ),
    ]
